### ISSUE TITLE
"Failed to connect" with EG32882, EG98668, EG99418 and EG900101. Home Assistant version 2022.6.7

### ISSUE THREAD

**Issue by Dominator55** [fsaris/home-assistant-awox#60]
Hi,
after downgrading the version of home assistant core to install bluepy and finally logging into my awox account, I cannot connect to any of my lights. All the connections timeout. Any idea what could be the issue? Log with debug attached.
[home-assistant.log](https://github.com/fsaris/home-assistant-awox/files/9087554/home-assistant.log)

**Comment by fsaris** [comment]
this should be fixed in the latest beta. could you test the beta release?

**Comment by fsaris** [comment]
see         # pair_char.write(message)

**Comment by Dominator55** [comment]
Unfortunately the issue is not fixed for me. All connection attempts end in asyncio.exceptions.CancelledError. I attach the log. Thank you for your efforts.
[home-assistant.log](https://github.com/fsaris/home-assistant-awox/files/9535250/home-assistant.log)

**Comment by fsaris** [comment]
now it looks that you run into a timeout. Could you try 0.1.3b3 that gives the BLE controller a little more time to connect before a timeout is triggered.
